gon:
  cue:
    security:
      authentication:
        jwt:
          base64-secret: KnJ3KSslcEh1PlFDJitydU5hWXZ4OyopYVRiSFNqIT4pZyhBeVM2KyJOVX4obldXWG02UlM1YGRDRDY1JDU4K3AoOyF+QF5uOVlxKmNMdVMpRHJHXVNYe2JXITdIbjI0SlArPj1FQyFLU3F6Z2BNNSpBNEEsNy5YJkVLYFJfdGF0UTUqcUxGflw7cFF6Qic3VVFQN3ondnVHJU06NCtHR1VjJi9hPz1jYid9WSc6Jl9XeEZQN0g4LDwoJC8oQ0RgXlY/UF4/V0htKHljIXdUYE0rMmpjN1BWXSkkeGE2d21XJVxlZEEzVXhZPnQnQDdZSExZLyUlYjdQSmR0eS1QWg==
          token-header: Authorization
          token-issuer: gon.cue
          token-prefix: Bearer
          token-validity-in-seconds: 86400
          token-validity-in-seconds-for-remember-me: 2592000
logging:
  file:
    name: logs/Application.log
server:
  port: 8888
spring:
  application:
    name: BaseFullstack
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: example
    url: jdbc:mysql://192.168.1.15:3306/MiscData?useSSL=false
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  swagger-ui:
    enabled: true